services:
  typesense:
    image: typesense/typesense:30.2
    container_name: typesense
    restart: on-failure
    ports:
      - '443:443'
    volumes:
      - ./typesense-data:/data
      - /etc/letsencrypt:/etc/letsencrypt:ro

    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_SSL_CERTIFICATE=${TYPESENSE_SSL_CERTIFICATE}
      - TYPESENSE_SSL_CERTIFICATE_KEY=${TYPESENSE_SSL_CERTIFICATE_KEY}
      - TYPESENSE_DATA_DIR=${TYPESENSE_DATA_DIR}
      - TYPESENSE_API_PORT=${TYPESENSE_API_PORT}
